"""
`ignis_notifications` provides a notification daemon which receives and manages notifications sent by
applications on GNU/Linux desktops that follow XDG Desktop Notifications Specification.

# Example
```python
from ignis_notifications import NotificationService

SERVICE = None

async fn run(service: NotificationService) -> None:
    await service.run()


fn setup_service() -> NotificationService:
    if SERVICE:
        return SERVICE
    else:
        service = NotificationService()
        # Run in the background
        asyncio.create_task(run())
        return service

service = setup_service()

# Access notifications
print(service.notifications)
```
"""

from typing import Any, Final, final

@final
class Action:
    """
    A notification action.
    
    Notification actions are typically presented as buttons in UI that allow user to
    interact with the application which sent the notification.
    """
    @property
    def action_key(self, /) -> str:
        """
        The identifier of the action.
        
        `"default"` means that the action is default.
        """
    def invoke(self, /) -> Any:
        """
        Invoke the action.
        """
    @property
    def label(self, /) -> str:
        """
        The localized string which should be displayed to the user.
        """
    @property
    def notification_id(self, /) -> int:
        """
        The ID of the notification this action belongs to.
        """

@final
class CloseReason:
    """
    A reason why the notification is closed.
    """
    DBusCall: Final[CloseReason]
    """
    The application requested to close the notification.
    """
    Dismissed: Final[CloseReason]
    """
    Dismissed by the user.
    
    Generated by a call to [`NotificationService.dismiss_notification`][]
    and [`Notification.dismiss`][]
    """
    Expired: Final[CloseReason]
    """
    Expired timeout. The notification was closed automatically upon expiration of the timeout.
    """
    Other: Final[CloseReason]
    """
    Undefined/reserved reasons.
    """
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...

@final
class Notification:
    """
    A desktop notification.
    """
    @property
    def actions(self, /) -> list[Action]:
        """
        List of actions for this notification. Can be empty.
        """
    @property
    def app_name(self, /) -> str:
        """
        The name of the application that sent the notification. Can be blank.
        """
    @property
    def body(self, /) -> str:
        """
        The optional detailed body text. Can be empty.
        """
    def dismiss(self, /) -> Any:
        """
        Dismisses this notification.
        """
    @property
    def icon(self, /) -> str |None:
        """
        The optional icon of the notification.
        
        It is either file path or icon name.
        """
    @property
    def id(self, /) -> int:
        """
        The unique non-zero identifer of the notification.
        """
    @property
    def summary(self, /) -> str:
        """
        The summary text briefly describing the notification.
        """
    @property
    def timeout(self, /) -> int:
        """
        The expire timeout of the notification.
        """
    @property
    def urgency(self, /) -> Urgency:
        """
        The urgency level of the notification.
        """

@final
class NotificationService:
    """
    A notification daemon that follows XDG Desktop Notifications Specification.
    """
    def __new__(cls, /) -> NotificationService: ...
    def clear_notifications(self, /) -> Any:
        """
        Clears the notification history.
        
        It dismisses each notification and notifies applications.
        
        # Warning
        It does **NOT** emit
        [`on_notification_closed`][] event for each notification.
        """
    def dismiss_notification(self, /, id: int) -> Any:
        """
        Dismiss a notification by its ID.
        
        The notification is removed from the history and application that sent the notification is notified through D-Bus.
        """
    def get_notification_by_id(self, /, id: int) -> Notification |None:
        """
        Returns a notification handle by notification ID.
        """
    def invoke_action(self, /, notification_id: int, action_key: str) -> Any:
        """
        Invokes an action by its action key and notification ID it belongs to.
        """
    @staticmethod
    def new_in_memory() -> NotificationService:
        """
        Creates a new instance of the service without any I/O operations.
        
        It doesn't load the notification history from file and doesn't save it consequently.
        This method can not fail and is guaranteed to return the instance.
        """
    @property
    def notifications(self, /) -> list[Notification]:
        """
        A list of notification handles.
        """
    def on_notification_closed(self, /, callback: Any) -> None:
        """
        Connect a callback to invoke when a notification is closed.
        
        Callback arguments:
        id (int) - The ID of the notification
        reason ([`CloseReason`][]) - The reason why this notification was
        closed.
        """
    def on_notified(self, /, callback: Any) -> None:
        """
        Connect a callback to invoke when a new notification is received.    
        
        Callback arguments:
        id (int) - The ID of the notification
        notification ([`Notification`][]) - The notification object.
        replace (bool) - whether this notification replaces an old one with the same ID.
        """
    def run(self, /) -> Any:
        """
        Runs the service.
        
        You have to call this this method in order to receive notifications and perform operations
        on them, such as dismissing or invoking actions.
        It creates D-Bus connection and registers D-Bus interface on the session bus.
        Must be called only once.
        """
    def settings(self, /) -> Settings:
        """
        Returns an instance of settings that affect behavior of the service.
        """

@final
class Settings:
    """
    Settings for [`NotificationService`][].
    
    This struct provides methods to change behavior of some parts of the service.
    """
    @property
    def default_timeout(self, /) -> int:
        """
        Returns the default timeout which is used when a notification doesn't specify timeout (-1).
        
        Has effect only if [`follow_xdg_timeout`][] and [`expire_by_default`][] are both `True`.
        
        Default: `3000`.
        """
    @default_timeout.setter
    def default_timeout(self, /, value: int) -> None: ...
    @property
    def expire_by_default(self, /) -> bool:
        """
        Returns whether to expire notifications if the timeout is not specified (when timeout is -1).
        
        If `true`, notifications expire after the timeout defined in [`default_timeout`][].
        
        Default: `false`.
        """
    @expire_by_default.setter
    def expire_by_default(self, /, value: bool) -> None: ...
    @property
    def follow_xdg_timeout(self, /) -> bool:
        """
        Returns whether to respect XDG Specification for timeout.
        
        If set to `false`, notifications never expire despite the value of [`Notification.timeout`][].
        Otherwise, behavior is based on notification's timeout:
        * `-1` - timeout value is taken from
        [`default_timeout`][].
        * `0` - the notification never expire
        * `>=0` - this timeout is used to expire the notification
        
        Default: `True`.
        """
    @follow_xdg_timeout.setter
    def follow_xdg_timeout(self, /, value: bool) -> None: ...

@final
class Urgency:
    """
    The urgency level of the notification.
    
    Represents how important is the notification and may affect how it's displayed in the graphical
    interface.
    """
    Critical: Final[Urgency]
    """
    A critical level of urgency.
    
    The notification requires user attention and should stand out from the rest of
    notifications.
    """
    Low: Final[Urgency]
    """
    A low level of urgency.
    
    Notification does not require immediate user attention.
    """
    Normal: Final[Urgency]
    """
    A normal level of urgency.
    
    For example, a notification about new message from a chat app.
    """
    def __int__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
