name: Bug Report
description: Something is not working right
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Already reported ? *
      description: Before opening a new bug report, please take a moment to search through the current open and closed issues to check if it already exists.
      options:
      - label: I have searched the existing open and closed issues.
        required: true

  - type: dropdown
    id: type
    attributes:
      label: Regression?
      description: |
        Regression means that something used to work but no longer does.
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: sysinfo
    attributes:
      label: System Information
      description: |
        Paste the output of `ignis systeminfo` here.

      value: "
        ```

        <Paste the output of the command here>

        ```"
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "What went wrong?"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: "How can someone else reproduce the issue?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs, images, videos, config files, CSS/SCSS files
      description: |
        Anything that can help. Please always ATTACH and not paste them.
        The log file is stored in ``~/.ignis/ignis.log``
