use pyo3::prelude::*;

/// `ignis_notifications` provides a notification daemon which receives and manages notifications sent by
/// applications on GNU/Linux desktops that follow XDG Desktop Notifications Specification.
///
/// # Example
/// ```python
/// from ignis_notifications import NotificationService
///
/// SERVICE = None
///
/// async fn run(service: NotificationService) -> None:
///     await service.run()
///
///
/// fn setup_service() -> NotificationService:
///     if SERVICE:
///         return SERVICE
///     else:
///         service = NotificationService()
///         # Run in the background
///         asyncio.create_task(run())
///         return service
///
/// service = setup_service()
///
/// # Access notifications
/// print(service.notifications)
/// ```
#[pymodule]
mod ignis_notifications {
    use notifications::CloseReason as RCloseReason;
    use notifications::NotificationService as RNotificationService;
    use notifications::Settings as RSettings;
    use notifications::Urgency as RUrgency;
    use notifications::{ActionHandle, NotificationHandle};
    use pyo3::{
        exceptions::{PyIOError, PyKeyError, PyOSError, PyRuntimeError, PyValueError},
        prelude::*,
    };

    use pyo3_async_runtimes;

    fn to_py_err(e: notifications::Error) -> PyErr {
        let msg = e.to_string();
        match e {
            notifications::Error::DBusError(_) => PyOSError::new_err(msg),
            notifications::Error::NoConnection => PyOSError::new_err(msg),
            notifications::Error::IOError(_) => PyIOError::new_err(msg),
            notifications::Error::JSONError(_) => PyValueError::new_err(msg),
            notifications::Error::NotificationNotFound(_) => PyKeyError::new_err(msg),
            notifications::Error::ConnectionInitializedTwice => PyRuntimeError::new_err(msg),
        }
    }

    /// The urgency level of the notification.
    ///
    /// Represents how important is the notification and may affect how it's displayed in the graphical
    /// interface.
    #[pyclass(from_py_object)]
    #[derive(Clone, Copy, PartialEq, Eq)]
    pub enum Urgency {
        /// A low level of urgency.
        ///
        /// Notification does not require immediate user attention.
        Low,

        /// A normal level of urgency.
        ///
        /// For example, a notification about new message from a chat app.
        Normal,

        /// A critical level of urgency.
        ///
        /// The notification requires user attention and should stand out from the rest of
        /// notifications.
        Critical,
    }

    /// A reason why the notification is closed.
    #[pyclass(from_py_object)]
    #[derive(Clone, Copy, PartialEq, Eq)]
    pub enum CloseReason {
        /// Expired timeout. The notification was closed automatically upon expiration of the timeout.
        Expired,

        /// Dismissed by the user.
        ///
        /// Generated by a call to [`NotificationService.dismiss_notification`][]
        /// and [`Notification.dismiss`][]
        Dismissed,

        /// The application requested to close the notification.
        DBusCall,

        /// Undefined/reserved reasons.
        Other,
    }

    impl From<&RUrgency> for Urgency {
        fn from(value: &RUrgency) -> Self {
            match value {
                RUrgency::Low => Urgency::Low,
                RUrgency::Normal => Urgency::Normal,
                RUrgency::Critical => Urgency::Critical,
            }
        }
    }

    impl From<&RCloseReason> for CloseReason {
        fn from(value: &RCloseReason) -> Self {
            match value {
                RCloseReason::Expired => Self::Expired,
                RCloseReason::Dismissed => Self::Dismissed,
                RCloseReason::DBusCall => Self::DBusCall,
                RCloseReason::Other => Self::Other,
            }
        }
    }

    /// A notification action.
    ///
    /// Notification actions are typically presented as buttons in UI that allow user to
    /// interact with the application which sent the notification.
    #[pyclass]
    struct Action {
        inner: ActionHandle,
    }

    #[pymethods]
    impl Action {
        /// The ID of the notification this action belongs to.
        #[getter]
        fn notification_id(&self) -> u32 {
            self.inner.notification_id()
        }

        /// The localized string which should be displayed to the user.
        #[getter]
        fn label(&self) -> String {
            self.inner.label()
        }

        /// The identifier of the action.
        ///
        /// `"default"` means that the action is default.
        #[getter]
        fn action_key(&self) -> String {
            self.inner.action_key()
        }

        /// Invoke the action.
        fn invoke<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();
            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner.invoke().await.map_err(to_py_err)
            })
        }
    }

    /// A desktop notification.
    #[pyclass]
    struct Notification {
        inner: NotificationHandle,
    }

    #[pymethods]
    impl Notification {
        /// The unique non-zero identifer of the notification.
        #[getter]
        fn id(&self) -> u32 {
            self.inner.id()
        }

        /// The name of the application that sent the notification. Can be blank.
        #[getter]
        fn app_name(&self) -> String {
            self.inner.app_name()
        }

        /// The optional icon of the notification.
        ///
        /// It is either file path or icon name.
        #[getter]
        fn icon(&self) -> Option<String> {
            self.inner.icon()
        }

        /// The summary text briefly describing the notification.
        #[getter]
        fn summary(&self) -> String {
            self.inner.summary()
        }

        /// The optional detailed body text. Can be empty.
        #[getter]
        fn body(&self) -> String {
            self.inner.body()
        }

        /// List of actions for this notification. Can be empty.
        #[getter]
        fn actions(&self) -> Vec<Action> {
            self.inner
                .actions()
                .into_iter()
                .map(|inner| Action { inner })
                .collect()
        }

        /// The urgency level of the notification.
        #[getter]
        fn urgency(&self) -> Urgency {
            (&self.inner.urgency()).into()
        }

        /// The expire timeout of the notification.
        #[getter]
        fn timeout(&self) -> i32 {
            self.inner.timeout()
        }

        /// Dismisses this notification.
        fn dismiss<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();
            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner.dismiss().await.map_err(to_py_err)
            })
        }

        /// Invokes a callback when this notification is closed.
        ///
        /// The following arguments are passed to the callback:
        /// reason ([`CloseReason`][]) - The reason why this notification was closed.
        fn on_closed<'py>(&self, callback: Py<PyAny>) {
            self.inner.on_closed(move |reason| {
                Python::attach(|py| {
                    if let Err(e) = callback.call1(py, (CloseReason::from(reason),)) {
                        e.print(py)
                    }
                })
            });
        }
    }

    /// Settings for [`NotificationService`][].
    ///
    /// This struct provides methods to change behavior of some parts of the service.
    #[pyclass]
    struct Settings {
        inner: RSettings,
    }

    #[pymethods]
    impl Settings {
        /// Returns whether to respect XDG Specification for timeout.
        ///
        /// If set to `false`, notifications never expire despite the value of [`Notification.timeout`][].
        /// Otherwise, behavior is based on notification's timeout:
        /// * `-1` - timeout value is taken from
        /// [`default_timeout`][].
        /// * `0` - the notification never expire
        /// * `>=0` - this timeout is used to expire the notification
        ///
        /// Default: `True`.
        #[getter]
        fn follow_xdg_timeout(&self) -> bool {
            self.inner.follow_xdg_timeout()
        }

        /// Returns the default timeout which is used when a notification doesn't specify timeout (-1).
        ///
        /// Has effect only if [`follow_xdg_timeout`][] and [`expire_by_default`][] are both `True`.
        ///
        /// Default: `3000`.
        #[getter]
        fn default_timeout(&self) -> u32 {
            self.inner.default_timeout()
        }

        /// Returns whether to expire notifications if the timeout is not specified (when timeout is -1).
        ///
        /// If `true`, notifications expire after the timeout defined in [`default_timeout`][].
        ///
        /// Default: `false`.
        #[getter]
        fn expire_by_default(&self) -> bool {
            self.inner.expire_by_default()
        }

        #[setter]
        fn set_follow_xdg_timeout(&self, value: bool) {
            self.inner.set_follow_xdg_timeout(value)
        }

        #[setter]
        fn set_default_timeout(&self, value: u32) {
            self.inner.set_default_timeout(value)
        }

        #[setter]
        fn set_expire_by_default(&self, value: bool) {
            self.inner.set_expire_by_default(value)
        }
    }

    /// A notification daemon that follows XDG Desktop Notifications Specification.
    #[pyclass]
    struct NotificationService {
        inner: RNotificationService,
    }

    #[pymethods]
    impl NotificationService {
        #[new]
        fn new() -> PyResult<Self> {
            Ok(Self {
                inner: RNotificationService::new(None).map_err(to_py_err)?,
            })
        }

        /// Creates a new instance of the service without any I/O operations.
        ///
        /// It doesn't load the notification history from file and doesn't save it consequently.
        /// This method can not fail and is guaranteed to return the instance.
        #[staticmethod]
        fn new_in_memory() -> Self {
            Self {
                inner: RNotificationService::new_in_memory(),
            }
        }

        /// Returns an instance of settings that affect behavior of the service.
        fn settings(&self) -> Settings {
            Settings {
                inner: self.inner.settings(),
            }
        }

        /// Runs the service.
        ///
        /// You have to call this this method in order to receive notifications and perform operations
        /// on them, such as dismissing or invoking actions.
        /// It creates D-Bus connection and registers D-Bus interface on the session bus.
        /// Must be called only once.
        fn run<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();

            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner.run().await.map_err(to_py_err)
            })
        }

        /// Dismiss a notification by its ID.
        ///
        /// The notification is removed from the history and application that sent the notification is notified through D-Bus.
        fn dismiss_notification<'py>(
            &self,
            py: Python<'py>,
            id: u32,
        ) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();

            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner.dismiss_notification(id).await.map_err(to_py_err)
            })
        }

        /// Invokes an action by its action key and notification ID it belongs to.
        fn invoke_action<'py>(
            &self,
            py: Python<'py>,
            notification_id: u32,
            action_key: String,
        ) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();

            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner
                    .invoke_action(notification_id, &action_key)
                    .await
                    .map_err(to_py_err)
            })
        }

        /// A list of notification handles.
        #[getter]
        fn notifications(&self) -> Vec<Notification> {
            self.inner
                .get_notifications()
                .into_iter()
                .map(|inner| Notification { inner })
                .collect()
        }

        /// Returns a notification handle by notification ID.
        fn get_notification_by_id(&self, id: u32) -> Option<Notification> {
            Some(Notification {
                inner: self.inner.get_notification_by_id(id)?,
            })
        }

        /// Clears the notification history.
        ///
        /// It dismisses each notification and notifies applications.
        ///
        /// # Warning
        /// It does **NOT** emit
        /// [`on_notification_closed`][] event for each notification.
        fn clear_notifications<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
            let inner = self.inner.clone();

            pyo3_async_runtimes::tokio::future_into_py(py, async move {
                inner.clear_notifications().await.map_err(to_py_err)
            })
        }

        /// Connect a callback to invoke when a new notification is received.    
        ///
        /// Callback arguments:
        /// id (int) - The ID of the notification
        /// notification ([`Notification`][]) - The notification object.
        /// replace (bool) - whether this notification replaces an old one with the same ID.
        fn on_notified(&self, callback: Py<PyAny>) {
            self.inner.on_notified(move |(id, handle, replace)| {
                Python::attach(|py| {
                    if let Err(e) = callback.call1(
                        py,
                        (
                            id,
                            Notification {
                                inner: handle.clone(),
                            },
                            replace,
                        ),
                    ) {
                        e.print(py)
                    }
                });
            });
        }

        /// Connect a callback to invoke when a notification is closed.
        ///
        /// Callback arguments:
        /// id (int) - The ID of the notification
        /// reason ([`CloseReason`][]) - The reason why this notification was
        /// closed.
        fn on_notification_closed(&self, callback: Py<PyAny>) {
            self.inner.on_notification_closed(move |(id, reason)| {
                Python::attach(|py| {
                    if let Err(e) = callback.call1(py, (id, CloseReason::from(reason))) {
                        e.print(py)
                    }
                })
            });
        }
    }
}
