clean:
    rm -R ./build

build:
    meson setup ./build -Dprofile=debug
    meson compile -C ./build

test: build
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}./build" \
    GI_TYPELIB_PATH="${GI_TYPELIB_PATH:+$GI_TYPELIB_PATH:}./build" \
    dbus-run-session -- pytest -s ./tests
