name: Create Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install meson
        run: |
          sudo apt update
          sudo apt install meson
      - name: Create tar file
        run: |
            cd ..
            meson subprojects download
            tar -czf "ignis-${{ github.ref_name }}.tar.gz" "ignis"
      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ../ignis-${{ github.ref_name }}.tar.gz