name: docs

on:
  push:
    branches:
      - main
    paths:
      - "ignis/**"
      - "docs/**"
      - ".github/workflows/latest_docs.yaml"
      - ".github/workflows/_build_docs.yaml"
      - ".github/workflows/_deploy_docs.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_deploy_docs.yaml
    with:
      DOC_TAG: "latest"