name: PyDoc

on:
  push:
    branches:
      - main
      - rust-rewrite

  pull_request:

jobs:
  doc:
    name: Build & Deploy Python doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build pydoc
        run: |
          nix develop .#pydocbuild --command bash -c '
            cd pydoc
            mkdocs build
          '

      - name: Deploy
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rust-rewrite')
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PY_DOC_DEPLOY_TOKEN }}
          external_repository: ignis-sh/py-doc
          publish_branch: gh-pages
          publish_dir: ./mkdocs/site
