name: Rust Doc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doc:
    name: Build & Deploy Rust doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - if: matrix.packages != ''
        name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libgdk-pixbuf-2.0-dev

      - name: Build documentation
        run: |
          cargo doc --all-features --no-deps \
                    -p notifications

          mkdir -p ./public
          cp -r ./target/doc/* ./public

          echo '<meta http-equiv="refresh" content="0; url=notifications/index.html">' > ./public/index.html
          touch ./public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.RUST_DOC_DEPLOY_TOKEN }}
          external_repository: ignis-sh/rust-doc
          publish_branch: main
          publish_dir: ./public
