name: Rust Doc

on:
  push:
    branches:
      - main
      - rust-rewrite

  pull_request:

jobs:
  doc:
    name: Build & Deploy Rust doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build documentation
        run: |
          nix develop .#rustci --command bash -c '
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc --no-deps
          '

      - name: Deploy
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rust-rewrite')
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.RUST_DOC_DEPLOY_TOKEN }}
          external_repository: ignis-sh/rust-doc
          publish_branch: gh-pages
          publish_dir: ./target/doc
