on: 
  push:
    paths:
      - "ignis/**"
      - ".github/workflows/static.yaml"
  pull_request:
    paths:
      - "ignis/**"

name: Static Analysis
jobs:
  mypy-check:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.txt
          pip install -r requirements.txt

      - name: Run mypy analysis
        run: |
          mypy
  
  ruff-check:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code
        run:
          ruff check ignis/

      - name: Check format
        run: ruff format ignis/ --check
