on: 
  push:
    branches:
      - main
    paths:
      - "ignis/**"
      - "examples/**"
      - ".github/workflows/static.yaml"
  pull_request:
    paths:
      - "ignis/**"
      - "examples/**"
      - ".github/workflows/static.yaml"

name: Static Analysis
jobs:
  mypy-check:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libcairo2-dev
          version: 1.0
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.txt
          grep -vE "PyGObject|setuptools" requirements.txt | pip install -r /dev/stdin

      - name: Run mypy analysis
        run: |
          mypy
  
  ruff-check:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code
        run: ruff check

      - name: Check format
        run: ruff format --check
